added blogs details
markodenic/awesome-tech-blogs pull request #331
Opened 2022-06-27 14:56 UTC by Vipul4439

2022-06-27 17:39 UTC, naresh-io commented
@Vipul4439 Please add the blog somewhere in the middle, not at the bottom or top.

2022-06-27 17:41 UTC, Vipul4439 commented
Sure

2022-06-28 05:23 UTC, naresh-io commented on data.js
> +    twitter: "https://twitter.com/Vipulso06279659",
Pleas fix your twitter handle, it should be `@Vipulso06279659` not the entire URL

2022-06-28 05:26 UTC, naresh-io requested changes

2022-06-28 05:26 UTC, naresh-io commented on data.js
> +    twitter: "https://twitter.com/Vipulso06279659",
Please update your Twitter handle. It should be just your handle `@Vipulso06279659`

2022-06-29 09:24 UTC, naresh-io commented
@Vipul4439 can you please resolve the merge conflicts

2022-07-09 11:57 UTC, merged