added economy blocked
markodenic/awesome-tech-blogs pull request #361
Opened 2022-08-17 05:31 UTC by TaylorJalpha

2022-08-23 11:30 UTC, naresh-io requested changes

2022-08-23 11:30 UTC, naresh-io commented on data.js
> +    ],
Please limit the number of tags to a maximum of 10.

2022-09-10 03:24 UTC, naresh-io commented
Please resolve the conflicts

2023-05-18 17:07 UTC, markodenic commented
Closing this due to inactivity. @TaylorJalpha feel free to open a new PR.

2023-05-18 17:07 UTC, closed without merging