Add Christine’s Blog
markodenic/awesome-tech-blogs pull request #393
Opened 2023-01-08 12:35 UTC by CBID2

WIP = Work in progress

2023-01-08 12:37 UTC, CBID2 commented
Hey @miohtama. I added my blog.

2023-01-16 05:11 UTC, AbbeyIT requested changes

2023-01-16 05:11 UTC, AbbeyIT commented on data.js
> +}
You need to put a comma here.

2023-01-16 05:53 UTC, CBID2 commented
Done @AbbeyIT

2023-01-28 16:26 UTC, markodenic approved these changes

2023-01-28 16:26 UTC, merged